name: 'Code Health'

# Set of validations run on each pull request and merged commits to master
on:
  push:
    branches:
      - master
    paths-ignore: # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-excluding-paths
      - '*.md'
      - 'examples/**'
      - 'LICENSE'
  pull_request: {}
  workflow_dispatch: {}

jobs:
  build-unit-test:
    runs-on: ubuntu-latest
    permissions: {}
    steps:
    - uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b
    - uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7
      with:
        go-version-file: 'go.mod'
        cache: false
    - id: cache-restore
      uses: actions/cache/restore@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: go-build-${{ hashFiles('**/go.sum') }}
    - name: Build
      run: make build
    - name: Unit Test
      run: make test
    - id: cache-save
      if: steps.cache-restore.outputs.cache-hit != 'true' && github.ref == 'refs/heads/master'
      uses: actions/cache/save@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: go-build-${{ hashFiles('**/go.sum') }}
  lint:
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b
      - uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7
        with:
          go-version-file: 'go.mod'
          cache: false
      - id: cache-restore
        uses: actions/cache/restore@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9
        with:
          key: go-lint-${{ hashFiles('**/go.sum', '**/GNUmakefile') }}
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
            ~/.cache/golangci-lint
      - id: golangci-lint
        uses: golangci/golangci-lint-action@a4f60bb28d35aeee14e6880718e0c85ff1882e64
        with:
          version: v1.57.2 # Also update GOLANGCI_VERSION variable in GNUmakefile when updating this version
          skip-cache: true
      - id: actionlint
        run: make tools && actionlint -verbose -color
        shell: bash  
      - id: cache-save
        if: steps.cache-restore.outputs.cache-hit != 'true' && github.ref == 'refs/heads/master'
        uses: actions/cache/save@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9
        with:
          key: go-lint-${{ hashFiles('**/go.sum', '**/GNUmakefile') }}
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
            ~/.cache/golangci-lint
  website-lint:
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b
      - uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7
        with:
          go-version-file: 'go.mod'
      - name: website lint
        run: make tools website-lint
  shellcheck:
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b
      - name: Run ShellCheck
        uses: bewuethr/shellcheck-action@d01912909579c4b1a335828b8fca197fbb8e0aa4
  call-acceptance-tests-workflow:
    needs: [build-unit-test, lint, shellcheck, website-lint]
    secrets: inherit
    uses: ./.github/workflows/acceptance-tests.yml
